food/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.login_view, name='home' ),
    path('inventory/', include('inventory.urls')),
    path('users/', include('users.urls')),
   
]

urlpatterns += staticfiles_urlpatterns()

inventory/urls.py
from django.urls import path
from .views import (
    inventory_list,
    create_product,
    update_product,
    detail_product,
    delete_product,
)

app_name = 'inventory'

urlpatterns = [
    path('',inventory_list.as_view(), name="list-view" ),
    path('create/',create_product.as_view(), name='create'),
    path('<int:pk>/',detail_product.as_view(), name='detail' ),
    path('<int:pk>/update/', update_product.as_view(), name='update'),
    path('<int:pk>/delete/', delete_product.as_view(), name='delete')


]

users/urls.py
from django.urls import path
from .views import (
    login_view,
    logout_view
)

app_name = 'users'

urlpatterns = [
    path('login/',login_view, name="login" ),
    path('logout/',logout_view, name='logout'),
]

inventory/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse



class categoria(models.Model):
    nombre = models.CharField(max_length=64, null=True)

    def __str__(self):
        return self.nombre

class articulo(models.Model):
    nombre = models.CharField(max_length=64, null=True)
    cantidad = models.IntegerField(null=True)
    slug = models.SlugField(max_length=128, null=True)
    #imagen = models.ImageField(null=True)
    categoria = models.ForeignKey(categoria, on_delete=models.CASCADE, blank=True)
    fecha_creacion = models.DateField(null=True)
    user = models.ForeignKey(User, on_delete=True, blank=True)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse("inventory:list-view")
    


    

users/models.py
from django.db import models

# Create your models here.

inventory/forms.py
from django import forms
from .models import articulo

class articulo_model_form(forms.ModelForm):
    class Meta:
        model = articulo
        fields = [
            'nombre',
            'cantidad',
            'slug',
            'categoria',
            'fecha_creacion',
            'user'
        ]

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms



class AgregarForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]
        email = forms.EmailField(max_length=128, help_text='Opcional')

inventory/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import articulo
from .forms import articulo_model_form
 

from django.views.generic import (
        ListView,
        CreateView,
        DetailView,
        UpdateView,
        DeleteView
)

class inventory_list(LoginRequiredMixin,ListView):
        template_name = 'inventory_list.html'
        queryset = articulo.objects.all()
        login_url = '/users/login/'

class create_product(LoginRequiredMixin,CreateView):
        template_name = 'create_product.html'
        form_class = articulo_model_form
        login_url = '/users/login/'

class update_product(LoginRequiredMixin,UpdateView):
        template_name = 'create_product.html'
        form_class = articulo_model_form
        success_message = "Registro actualizado exitosamente"
        login_url = '/users/login/'

        def get_object(self):
                id_ = self.kwargs.get("pk")
                return get_object_or_404(articulo, pk=id_)

class detail_product(LoginRequiredMixin,DetailView):
        template_name = 'detail_product.html'
        form_class = articulo_model_form     
        login_url = '/users/login/'   

        def get_object(self):
                id_ = self.kwargs.get("pk")
                return get_object_or_404(articulo, pk=id_)

class delete_product(LoginRequiredMixin,DeleteView):
        model = articulo
        success_url = reverse_lazy('inventory:list-view')
        login_url = '/users/login/'

        def get_object(self):
                id_ = self.kwargs.get("pk")
                return get_object_or_404(articulo, pk=id_)

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from .forms import AgregarForm

def login_view(request):
    if(request.method == "POST"):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("inventory:list-view")
    else:
        if request.user.is_authenticated:
            return redirect("inventory:list-view")
        else:
            form = AuthenticationForm(request)
    return render(request, 'login.html', {'form':form})


def logout_view(request):
    logout(request)
    return redirect('users:login')

inventory/templates/create_product.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags  %}
{% block content%}
<!-- contact -->
  <section id="contact" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="header-h">Agregar Producto</h1>
          <p class="header-p">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy
            <br>nibh euismod tincidunt ut laoreet dolore magna aliquam. </p>
        </div>
      </div>
      <div class="row msg-row">        
        <div class="col-md-8 col-sm-8">
          <form action="." method="post" role="form" class="">
           {% csrf_token %}
            <div class="col-md-6 col-sm-6">
              <div class="form-group label-floating is-empty">
                {{ form.nombre | as_crispy_field }}
              </div>

            </div>
            <div class="col-md-6 col-sm-6 ">
              <div class="form-group">
               {{ form.cantidad | as_crispy_field }}
              </div>
            </div>
            <div class="col-md-6 col-sm-6 ">
              <div class="form-group">
                {{ form.slug | as_crispy_field}}
              </div>
            </div>
            <div class="col-md-6 col-sm-6">
              <div class="form-group">
                {{ form.categoria | as_crispy_field}}
              </div>
            </div>
            <div class="col-md-6 col-sm-6 ">
              <div class="form-group">
               {{ form.fecha_creacion | as_crispy_field}}
              </div>
            </div>
            <div class="col-md-6 col-sm-6 ">
              <div class="form-group">
                {{ form.user | as_crispy_field }}
              </div>
            </div>            
            <div class="col-md-12 btnpad">
              <div class="contacts-btn-pad">
                <button type='submit' class="contacts-btn">Guardar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <!-- / contact -->

  {% endblock%}

inventory/templates/detail_product.html
{% extends "base_layout.html" %}
{% block content %}
<!--about-->
  <section id="about" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center marb-35">
          <h1 class="header-h">{{ object.nombre }}</h1>          
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <div class="col-md-6 col-sm-6">
            <div class="about-info">
              <h2 class="heading">{{ object.categoria }}</h2>
              <div class="details-list">
                <ul>
                  <li><i class="fa fa-check"></i>Cantidad : {{ object.cantidad }}</li>
                  <li><i class="fa fa-check"></i>Fecha : {{object.fecha_creacion}}</li>                  
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6">
            <img src="img/res01.jpg" alt="Image" class="img-responsive">
          </div>
        </div>
        <div class="col-md-6 text-right btnpad">            
              <div class="contacts-btn-pad">
                <button type='button' onclick="location.href= '{% url 'inventory:update' pk=object.pk %}'"  class="contacts-btn">Editar</button>
              </div>
        </div>
        <div class="col-md-6 btnpad"> 
            <form action="{% url 'inventory:delete' pk=object.pk %}" method="post">
            {% csrf_token %}         
              <div class="contacts-btn-pad">
                <button type='submit'  class="contacts-btn-delete">Eliminar</button>
              </div>
        </div>
      </div>
    </div>
  </section>
  <!--/about-->
{% endblock content %}

inventory/templates/inventory_list.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block content %}
 <!-- menu -->
  <section id="menu-list" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center marb-35">
          <h1 class="header-h">Food List</h1>
          <p class="header-p">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy
            <br>nibh euismod tincidunt ut laoreet dolore magna aliquam. </p>
        </div>

        <div class="col-md-12  text-center" id="menu-flters">
          <ul>
            <li><a class="filter active" data-filter=".menu-restaurant">Show All</a></li>           
          </ul>
        </div>
        {% for instance in object_list %}
        <div id="menu-wrapper">
          <div class="breakfast menu-restaurant">
            <span class="clearfix">
              <a class="menu-title" href="{% url 'inventory:detail' pk=instance.pk %}" data-meal-img="{% static 'assets/img/restaurant/rib.jpg' %}">{{ instance.nombre}}</a>
              <span style="left: 166px; right: 44px;" class="menu-line"></span>
              <span class="menu-price">{{instance.cantidad}}</span>
            </span>
            <span class="menu-subtitle">Neque porro quisquam est qui dolorem</span>
          </div>         
        {% endfor %}
      </div>
    </div>
  </section>
  <!--/ menu -->

  {% endblock %}

templates/banner.html
<!--banner-->
  <section id="banner">
    <div class="bg-color">
      <header id="header">
        <div class="container">
          <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="{% url 'users:logout' %}">Logout</a>
            <a href="#event">Buscar</a>
            <a href="#menu-list">Menu</a>            
          </div>
          <!-- Use any element to open the sidenav -->
          <span onclick="openNav()" class="pull-right menu-icon">☰</span>
        </div>
      </header>
      <div class="container">
        <div class="row">
          <div class="inner text-center">
            <a  href="{% url 'inventory:list-view'  %}"><h1 class="logo-name">Delicious</h1></a>
            <h2>Food To fit your lifestyle & health.</h2>
            <p>Specialized in Indian Cuisine!!</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- / banner -->

templates/base_layout.html
{% load static from staticfiles %}
<!doctype html>
<html lang='es'>
{% include "head.html" %}
    <body>
    {% include "banner.html" %}
    {% block content %}
    {% endblock %}
    {% include "footer.html" %}
    {% include "scripts.html" %}
    </body>
</html>

templates/footer.html
 <!-- footer -->
  <footer class="footer text-center">
    <div class="footer-top">
      <div class="row">
        <div class="col-md-offset-3 col-md-6 text-center">
          <div class="widget">
            <h4 class="widget-title">Delicious</h4>
            <address>324 Ellte Road<br>Delhi, DL 110013</address>
            <div class="social-list">
              <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            </div>
            <p class="copyright clear-float">
              © Delicious Theme. All Rights Reserved
              <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Delicious
                -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
              </div>
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- / footer -->

templates/head.html
{% load static from staticfiles %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Delicious</title>
  <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
  <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy|Bree+Serif|Candal|PT+Sans">
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <!-- =======================================================
    Theme Name: Delicious
    Theme URL: https://bootstrapmade.com/delicious-free-restaurant-bootstrap-theme/
    Author: BootstrapMade.com
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Delicious</title>
  <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
  <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy|Bree+Serif|Candal|PT+Sans">
  <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <!-- =======================================================
    Theme Name: Delicious
    Theme URL: https://bootstrapmade.com/delicious-free-restaurant-bootstrap-theme/
    Author: BootstrapMade.com
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
 

  <script src="js/jquery.min.js"></script>
  <script src="js/jquery.easing.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/custom.js"></script>
  <script src="contactform/contactform.js"></script>

</body>

</html>

templates/scripts.html
{% load static from staticfiles %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/custom.js'%}"></script>
<script src="{% static 'contactform/contactform.js'%}"></script>

users/templates/login.html
{% load static from staticfiles %}
{% load crispy_forms_tags  %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Delicious</title>
  <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
  <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy|Bree+Serif|Candal|PT+Sans">
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <!-- =======================================================
    Theme Name: Delicious
    Theme URL: https://bootstrapmade.com/delicious-free-restaurant-bootstrap-theme/
    Author: BootstrapMade.com
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
 <section id="contact" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="header-h">Log In</h1>
          <p class="header-p">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy
            <br>nibh euismod tincidunt ut laoreet dolore magna aliquam. </p>
        </div>
      </div>
      <div class="row msg-row">        
        <div class="col-md-12 col-sm-12">
          <form action="." method="post" role="form" class="">
           {% csrf_token %}
            <div class="col-md-12 text-center">
              <div class="form-group label-floating is-empty">
                {{ form.username | as_crispy_field }}
              </div>
            </div>
            <div class="col-md-12 text-center">
              <div class="form-group label-floating is-empty">
                {{ form.password | as_crispy_field }}
              </div>
            </div>            
                      
            <div class="col-md-12 btnpad text-center">
              <div class="contacts-btn-pad">
                <button type='submit' class="contacts-btn">Aceptar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

  <script src="js/jquery.min.js"></script>
  <script src="js/jquery.easing.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/custom.js"></script>
  <script src="contactform/contactform.js"></script>

</body>

</html>